//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAppThree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popis
    {
        public int PopisId { get; set; }
        public int KolegijId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Kolegij Kolegij { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
