//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAppThree.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentiDBEntities2 : DbContext
    {
        public StudentiDBEntities2()
            : base("name=StudentiDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kolegij> Kolegij { get; set; }
        public virtual DbSet<Popis> Popis { get; set; }
        public virtual DbSet<Studenti> Studenti { get; set; }
    }
}
